# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        
      - name: Check node v
        run: node -v
        
      - name: Install deps
        run: npm i
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e -- --headless
#           wait-on: 'http://localhost:8080'
          # wait for 2 minutes for the server to respond
#           wait-on-timeout: 60
#         run: npm run test:e2e
