name: Run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        
      - name: Check node v
        run: node -v
        
      - name: Install deps
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e -- --headless
