# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish package

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Check node v
        run: node -v
        
      - name: Install deps
        run: npm ci
      
      # - name: Run unit tests
      #   run: npm run test:unit

      - name: Start app in background
        run: npm run dev &
      
      - name: Run e2e tests
        uses: cypress-io/github-action@v3
        with:
          command: npm run test:e2e -- --headless

  publish:
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build-pkg

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
